### ISSUE TITLE
Please support tag system

### ISSUE THREAD

**Issue by prageeth-peiris** [webbingbrasil/filament-advancedfilter#2]
## Describe the ideal solution or feature request
Maintain Semantic Versioning  for the package

## Difficulty, impact, and usage score
| Technical difficulty | User goals | Usage frequency |
|--------------------| --------------------| --------------------|
| small |  Updating the package with composer  |  Daily  |

## How does this tie into our current project?
This will be useful for those who already using this great package !

**Comment by dmandrade** [comment]
thanks for the warning, I already added them
