### ISSUE TITLE
In Filament v3 getRelationshipTitleColumnName has been replaced with getRelationshipTitleAttribute

### ISSUE THREAD

**Issue by iRajul** [webbingbrasil/filament-advancedfilter#31]
**Describe the bug**
In Filament v3 `getRelationshipTitleColumnName` has been replaced with `getRelationshipTitleAttribute`
IN src/Concerns/HasClauses.php ::apply function this needs to be change. 

Right now relationship is not working on filters.

**To Reproduce**
1. Use relationship on filter, it will not work.

**Expected behavior**
Filter should work with relationship.

**Screenshots**

**Additional context**

**Comment by iRajul** [comment]
created pull request for the same: 
https://github.com/webbingbrasil/filament-advancedfilter/pull/32

**Comment by dmandrade** [comment]
PR #32 was closed. So I approved #34 which fix the same problem.
