### ISSUE TITLE
Getting `ErrorException: Undefined array key ""` when selecting blank option

### ISSUE THREAD

**Issue by devadattas** [webbingbrasil/filament-advancedfilter#9]
**Describe the bug**
The error `Undefined array key ""` when we select the option "Select an option" from the matcher type dropdown once another option is selected.

**To Reproduce**
1. Go to a table with Filters
2. Click on 'Filter Icon'
    <img width="315" alt="image" src="https://user-images.githubusercontent.com/56180/198752023-bda7951c-e03c-4117-8410-ef95beedb655.png">
3. Select any matcher type from the dropdown.
    <img width="313" alt="image" src="https://user-images.githubusercontent.com/56180/198752089-c9d89716-cd13-452b-bc87-2ebf977ad15f.png">
4. Now select "Select an Option"
    <img width="312" alt="image" src="https://user-images.githubusercontent.com/56180/198752136-0ec47fd6-caa1-4d15-a234-621519bb2d89.png">
5. Following error appears:
    <img width="1565" alt="image" src="https://user-images.githubusercontent.com/56180/198751950-f4af58b4-f535-40de-8d16-0f6ffc8fe515.png">

**Expected behavior**
No error should appear.

**Screenshots**
<img width="1565" alt="image" src="https://user-images.githubusercontent.com/56180/198751950-f4af58b4-f535-40de-8d16-0f6ffc8fe515.png">

**Comment by erenmustafaozdal** [comment]
This error persists for NumberFilter and BooleanFilter.
